#!/usr/bin/env bash

source /etc/AIInAAL/AIInAAL_path
source $AIInAALdir/AIInAAL_env/bin/activate

var1=$(echo $1)
var2=$(echo $2)

case $var1 in
    install)
        case $var2 in
            ComfyUI)
                $AIInAALdir/Scripts/AIInAAL-install-ComfyUI.sh
            ;;
            comfyui)
                $AIInAALdir/Scripts/AIInAAL-install-ComfyUI.sh
            ;;
            Ollama)
                $AIInAALdir/Scripts/AIInAAL-install-Ollama.sh
            ;;
            ollama)
                $AIInAALdir/Scripts/AIInAAL-install-Ollama.sh
            ;;
            SwarmUI)
                $AIInAALdir/Scripts/AIInAAL-install-SwarmUI.sh
            ;;
            swarmui)
                $AIInAALdir/Scripts/AIInAAL-install-SwarmUI.sh
            ;;
            Fooocus)
                $AIInAALdir/Scripts/AIInAAL-install-Fooocus.sh
            ;;
            fooocus)
                $AIInAALdir/Scripts/AIInAAL-install-Fooocus.sh
            ;;
            RoopUL)
                $AIInAALdir/Scripts/AIInAAL-install-RoopUL.sh
            ;;
            roopul)
                $AIInAALdir/Scripts/AIInAAL-install-RoopUL.sh
            ;;
            OmniGen)
                $AIInAALdir/Scripts/AIInAAL-install-OmniGen.sh
            ;;
            omnigen)
                $AIInAALdir/Scripts/AIInAAL-install-OmniGen.sh
            ;;
            CrewAI)
                $AIInAALdir/Scripts/AIInAAL-install-CrewAI.sh
            ;;
            crewai)
                $AIInAALdir/Scripts/AIInAAL-install-CrewAI.sh
            ;;
            F5-TTS)
                $AIInAALdir/Scripts/AIInAAL-install-F5-TTS.sh
            ;;
            f5-tts)
                $AIInAALdir/Scripts/AIInAAL-install-F5-TTS.sh
            ;;
            *)
                echo "You have entered an invalid command. You may install the following:"
                echo "ComfyUI, Ollama, SwarmUI, OmniGen, Fooocus, RoopUL, CrewAI, F5-TTS"
            ;;
        esac
;;
    update)
        case $var2 in
            AIInAAL)
                source $AIInAALdir/libref
                AIInAAL_update
            ;;
            aiinaal)
                source $AIInAALdir/libref
                AIInAAL_update
            ;;
            Intel)
                pip install --upgrade -r $AIInAALdir/Scripts/intel_requirements.txt
                #echo "Temporarily disabled due to custom torch build testing..."
            ;;
            intel)
                pip install --upgrade -r $AIInAALdir/Scripts/intel_requirements.txt
                #echo "Temporarily disabled due to custom torch build testing..."
            ;;
            Torch)
                pip install --upgrade -r $AIInAALdir/Scripts/torch_requirements.txt
                set UR_L0_ENABLE_SYSMAN_ENV_DEFAULT=0
                export UR_L0_ENABLE_SYSMAN_ENV_DEFAULT=0
                #echo "Temporarily disabled due to custom torch build testing..."
            ;;
            torch)
                pip install --upgrade -r $AIInAALdir/Scripts/torch_requirements.txt
                set UR_L0_ENABLE_SYSMAN_ENV_DEFAULT=0
                export UR_L0_ENABLE_SYSMAN_ENV_DEFAULT=0
                #echo "Temporarily disabled due to custom torch build testing..."
            ;;
        esac
;;
    run)
        case $var2 in
            ComfyUI)
                $AIInAALdir/ComfyUI/ComfyUI-Start.sh
            ;;
            comfyui)
                $AIInAALdir/ComfyUI/ComfyUI-Start.sh
            ;;
            Ollama)
                $AIInAALdir/Ollama/Ollama-Start.sh
            ;;
            ollama)
                $AIInAALdir/Ollama/Ollama-Start.sh
            ;;
            Fooocus)
                $AIInAALdir/Fooocus/Fooocus-Start.sh
            ;;
            fooocus)
                $AIInAALdir/Fooocus/Fooocus-Start.sh
            ;;
            RoopUL)
                $AIInAALdir/RoopUL/RoopUL-Start.sh
            ;;
            roopul)
                $AIInAALdir/RoopUL/RoopUL-Start.sh
            ;;
            OmniGen)
                $AIInAALdir/OmniGen/OmniGen-Start.sh
            ;;
            omnigen)
                $AIInAALdir/OmniGen/OmniGen-Start.sh
            ;;
            CrewAI)
                $AIInAALdir/CrewAI/CrewAI-Start.sh
            ;;
            crewai)
                $AIInAALdir/CrewAI/CrewAI-Start.sh
            ;;
            F5-TTS)
                $AIInAALdir/F5-TTS/F5-TTS-Start.sh
            ;;
            f5-tts)
                $AIInAALdir/F5-TTS/F5-TTS-Start.sh
            ;;
            *)
                echo "You have entered an invalid command. You may run the following:"
                echo "ComfyUI, Ollama, OmniGen, Fooocus, RoopUL, CrewAI, F5-TTS"
            ;;
        esac
;;
    AIInAAL_env)
        Deb4AIInAAL -q "$3"
;;
    AIInAAL12_env)
        Deb4AIInAAL12 -q "$3"
;;
esac

