#!/usr/bin/env bash

source /etc/AINvAL580/AINvAL580_path
source $AINvAL580dir/AINvAL580_env/bin/activate

var1=$(echo $1)
var2=$(echo $2)

case $var1 in
    install)
        case $var2 in
            ComfyUI)
                $AINvAL580dir/Scripts/AINvAL580-install-ComfyUI.sh
            ;;
            comfyui)
                $AINvAL580dir/Scripts/AINvAL580-install-ComfyUI.sh
            ;;
            Ollama)
                $AINvAL580dir/Scripts/AINvAL580-install-Ollama.sh
            ;;
            ollama)
                $AINvAL580dir/Scripts/AINvAL580-install-Ollama.sh
            ;;
            SwarmUI)
                $AINvAL580dir/Scripts/AINvAL580-install-SwarmUI.sh
            ;;
            swarmui)
                $AINvAL580dir/Scripts/AINvAL580-install-SwarmUI.sh
            ;;
            Fooocus)
                $AINvAL580dir/Scripts/AINvAL580-install-Fooocus.sh
            ;;
            fooocus)
                $AINvAL580dir/Scripts/AINvAL580-install-Fooocus.sh
            ;;
            RoopUL)
                $AINvAL580dir/Scripts/AINvAL580-install-RoopUL.sh
            ;;
            roopul)
                $AINvAL580dir/Scripts/AINvAL580-install-RoopUL.sh
            ;;
            OmniGen)
                $AINvAL580dir/Scripts/AINvAL580-install-OmniGen.sh
            ;;
            omnigen)
                $AINvAL580dir/Scripts/AINvAL580-install-OmniGen.sh
            ;;
            CrewAI)
                $AINvAL580dir/Scripts/AINvAL580-install-CrewAI.sh
            ;;
            crewai)
                $AINvAL580dir/Scripts/AINvAL580-install-CrewAI.sh
            ;;
            F5-TTS)
                $AINvAL580dir/Scripts/AINvAL580-install-F5-TTS.sh
            ;;
            f5-tts)
                $AINvAL580dir/Scripts/AINvAL580-install-F5-TTS.sh
            ;;
            *)
                echo "You have entered an invalid command. You may install the following:"
                echo "ComfyUI, Ollama, SwarmUI, OmniGen, Fooocus, RoopUL, CrewAI, F5-TTS"
            ;;
        esac
;;
    update)
        case $var2 in
            AINvAL580)
                source $AINvAL580dir/libref
                AINvAL580_update
            ;;
            AINvAL580)
                source $AINvAL580dir/libref
                AINvAL580_update
            ;;
            ainval)
                source $AINvAL580dir/libref
                AINvAL580_update
            ;;
            ainval580)
                source $AINvAL580dir/libref
                AINvAL580_update
            ;;
            Torch)
                source $AINvAL580dir/libref
                AINvAL580_update_Torch
            ;;
            torch)
                source $AINvAL580dir/libref
                AINvAL580_update_Torch
            ;;
        esac
;;
    run)
        case $var2 in
            ComfyUI)
                $AINvAL580dir/ComfyUI/ComfyUI-Start.sh
            ;;
            comfyui)
                $AINvAL580dir/ComfyUI/ComfyUI-Start.sh
            ;;
            Ollama)
                $AINvAL580dir/Ollama/Ollama-Start.sh
            ;;
            ollama)
                $AINvAL580dir/Ollama/Ollama-Start.sh
            ;;
            Fooocus)
                $AINvAL580dir/Fooocus/Fooocus-Start.sh
            ;;
            fooocus)
                $AINvAL580dir/Fooocus/Fooocus-Start.sh
            ;;
            RoopUL)
                $AINvAL580dir/RoopUL/RoopUL-Start.sh
            ;;
            roopul)
                $AINvAL580dir/RoopUL/RoopUL-Start.sh
            ;;
            OmniGen)
                $AINvAL580dir/OmniGen/OmniGen-Start.sh
            ;;
            omnigen)
                $AINvAL580dir/OmniGen/OmniGen-Start.sh
            ;;
            CrewAI)
                $AINvAL580dir/CrewAI/CrewAI-Start.sh
            ;;
            crewai)
                $AINvAL580dir/CrewAI/CrewAI-Start.sh
            ;;
            F5-TTS)
                $AINvAL580dir/F5-TTS/F5-TTS-Start.sh
            ;;
            f5-tts)
                $AINvAL580dir/F5-TTS/F5-TTS-Start.sh
            ;;
            *)
                echo "You have entered an invalid command. You may run the following:"
                echo "ComfyUI, Ollama, OmniGen, Fooocus, RoopUL, CrewAI, F5-TTS"
            ;;
        esac
;;
    AINvAL580_env)
        Deb4AINvAL580 -q "$3"
;;
    AINvAL58012_env)
        Deb4AINvAL58012 -q "$3"
;;
esac

