#!/usr/bin/env bash

source /etc/AINvAL580/AINvAL580_path

echo "Running librefgen..."
cd $AINvAL580dir
echo "Regenerating LIBREF..."
echo "pdirectory=$pdirectory" > $AINvAL580dir/libref
echo "AINvAL580dir=$AINvAL580dir" >> $AINvAL580dir/libref
echo "" >> $AINvAL580dir/libref
echo "export LD_LIBRARY_PATH=/lib" >> $AINvAL580dir/libref

echo "AINvAL580_update () {" >> $AINvAL580dir/libref
echo "    hfcache=$(echo ~)/.cache/huggingface" >> $AINvAL580dir/libref
echo "    cd $AINvAL580dir" >> $AINvAL580dir/libref
echo "    git switch main" >> $AINvAL580dir/libref
echo "    git reset --hard HEAD" >> $AINvAL580dir/libref
echo "    git pull" >> $AINvAL580dir/libref
echo "    rm -Rf $AINvAL580dir/AINvAL580_env/lib/python3.12/site-packages/~*" >> $AINvAL580dir/libref
echo "    rm -Rf $AINvAL580dir/AINvAL580_env_inf/lib/python3.12/site-packages/~*" >> $AINvAL580dir/libref
echo "    sed -i 's/\r//' $AINvAL580dir/AINvAL580_install.sh 2> /dev/null" >> $AINvAL580dir/libref
echo "    cd $AINvAL580dir/Scripts" >> $AINvAL580dir/libref
echo "    for file in *.sh" >> $AINvAL580dir/libref
echo "      do" >> $AINvAL580dir/libref
echo "      sed -i 's/\r//' \$file 2> /dev/null" >> $AINvAL580dir/libref
echo "    done" >> $AINvAL580dir/libref
echo "    cd \$AINvAL580dir" >> $AINvAL580dir/libref
echo "    for d in */" >> $AINvAL580dir/libref
echo "      do" >> $AINvAL580dir/libref
echo "      ainvalpkg1=\$(echo \$d | cut -d/ -f1)" >> $AINvAL580dir/libref 
echo "      sed -i 's/\r//' \$ainvalpkg1/libref-\$ainvalpkg1 2> /dev/null" >> $AINvAL580dir/libref
echo "    done" >> $AINvAL580dir/libref
echo "    Scripts/librefgen" >> $AINvAL580dir/libref
echo "    pip install --upgrade pip" >> $AINvAL580dir/libref
echo "    rm -R \"\$hfcache\"" >> $AINvAL580dir/libref
echo "    ln -sf \"$AINvAL580dir/shared/HF\" \"\$hfcache\"" >> $AINvAL580dir/libref
echo "    pip install --upgrade -r $AINvAL580dir/Scripts/requirements_AINvAL580.txt" >> $AINvAL580dir/libref

echo "}" >> $AINvAL580dir/libref

echo "AINvAL580_update_Torch () {" >> $AINvAL580dir/libref
echo "    pip install --upgrade -r $AINvAL580dir/Scripts/requirements_AINvAL580_torch.txt" >> $AINvAL580dir/libref
echo "}" >> $AINvAL580dir/libref

echo "EOF_fix () {" >> $AINvAL580dir/libref
echo "echo    Correcting any BS WINBLOWS carriage return entries in bash scripts..." >> $AINvAL580dir/libref
echo "    cd $AINvAL580dir/\$ainvalpkg" >> $AINvAL580dir/libref
echo "    for file in libref-*" >> $AINvAL580dir/libref
echo "      do" >> $AINvAL580dir/libref
echo "      sed -i 's/\r//' \$file 2> /dev/null" >> $AINvAL580dir/libref
echo "    done" >> $AINvAL580dir/libref
echo "}" >> $AINvAL580dir/libref
echo "LIBREF regenerated."
